
dist: trusty
sudo: false
os:
    - linux
services:
    - docker
language: cpp
compiler: g++
script: 
    - docker run anitagov/ubuntu-tools:1.3
    - apt-get -y update
    - apt-get -y install linux-generic
    - sudo make -C drivers
    - find drivers -name isgx.ko -print
